### ISSUE TITLE
Corona Info Page - Patient

### ISSUE THREAD

**Issue by explowable** [explowable/crisis-management#4]
# :sparkles: Corona Info Page :sparkles:
A short description why you are creating this story...

## 🚀Goal
A clear and concise description of the goal the user/role want to archive...

### Short Description
1. BlaBlaBlub...

### 🛠️Tasks
- [ ] Handle Configuration Update
- [ ] Configuration Update - State response
- [ ] Handle Command Event
- [ ] State Updates

## 🔥Acceptance Criteria
- [ ] The web app triggers a device update.
- [ ] The device state is updating.

### 🌍Links
* [Archive a card](https://help.github.com/articles/archiving-cards-on-a-project-board/)

### :squirrel:Relates To
Feature: #
Bug: #
Card: [Card1](https://help.github.com/articles/archiving-cards-on-a-project-board/)
